title: Paulo Oliveira
email: paulovt7@gmail.com
description: > #
url: "https://blog.pauloliveira.dev"
twitter_username: paulovcdo
github_username:  pvoliveira
theme: jekyll-theme-cayman
timezone: Europe/Lisbon