baseURL: https://blog.pauloliveira.dev/
disablePathToLower: true
languageCode: pt-BR
title: Paulo Oliveira
theme: anubis
disqusShortname: disqus_F6ZSYN9eM0
params:
  description: |
    Meu nome é Paulo Oliveira, e aqui é o lugar onde compartilho um pouco sobre desenvolvimento de software.
Menus:
  main:
    - Name: "GitHub"
      URL: "https://github.com/pvoliveira/"
    - Name: "LinkedIn"
      URL: "https://www.linkedin.com/in/paulovitorcorreadeoliveira/"
